export {default as HomePage} from './HomePage'
export {default as ContactPage} from './ContactPage'
export {default as CommunityPage} from './CommunityPage'
export {default as ResourcePage} from './ResourcePage'
export {default as JoinUsPage} from './JoinUsPage'
export {default as SignINUPPage} from './SignINUPPage'